package com.example.vehiclessale.utils

object Const {
    const val FRAGMENT_EDIT_USER_MAKE_PHONE_CALL = "FRAGMENT_EDIT_USER_MAKE_PHONE_CALL"
    const val FRAGMENT_EDIT_USER_MAKE_PHONE_CALL_BY_ZALO =
        "FRAGMENT_EDIT_USER_MAKE_PHONE_CALL_BY_ZALO"
    const val FRAGMENT_EDIT_USER_SEND_MESSAGE = "FRAGMENT_EDIT_USER_SEND_MESSAGE"

    const val FRAGMENT_HOME_SHOW_CAR = "FRAGMENT_HOME_SHOW_CAR"
    const val FRAGMENT_HOME_SHOW_MOTORBIKE = "FRAGMENT_HOME_SHOW_MOTORBIKE"
    const val FRAGMENT_HOME_SHOW_ELECTRIC_BIKE = "FRAGMENT_HOME_SHOW_ELECTRIC_BIKE"

}